config/routes.rb
Rails.application.routes.draw do    
  root "events#index"

  get "events/filter/:filter" => "events#index", as: :filtered_events

  resources :events do
    resources :registrations
    resources :likes
  end

  resource :session, only: [:new, :create, :destroy]
  resources :users
  resources :categories
  
  get "signup" => "users#new"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :registrations, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_events, through: :likes, source: :event
  
  has_secure_password

  validates :name, presence: true

  validates :email, format: { with: /\S+@\S+/ },
                    uniqueness: { case_sensitive: false }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signin, except: [:new, :create]
  before_action :require_correct_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @registrations = @user.registrations
    @liked_events = @user.liked_events
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "Thanks for signing up!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "Account successfully updated!"
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil
    redirect_to events_url, alert: "Account successfully deleted!"
  end

  private

  def require_correct_user
    @user = User.find(params[:id])
    redirect_to events_url unless current_user?(@user)
  end

  def user_params
    params.require(:user).
      permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, styles: "rounded")
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: styles)
  end
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |f| %>
  <div class="form-group row">

    <%= render "shared/errors", object: user %>

    <div class="col-sm-12 my-2">
      <%= f.label :name, class: "font-weight-bold" %>
      <%= f.text_field :name, autofocus: true, class: "form-control" %>
    </div>

    <div class="col-sm-12 my-2">
      <%= f.label :email, class: "font-weight-bold" %>
      <%= f.email_field :email, class: "form-control" %>
    </div>

    <div class="col-sm-12 my-2">
      <%= f.label :password, class: "font-weight-bold" %>
      <%= f.password_field :password, class: "form-control" %>
    </div>

    <div class="col-sm-12 my-2">
      <%= f.label :password_confirmation, "Confirm Password", class: "font-weight-bold" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>
  </div>

  <% if user.new_record? %>
    <%= f.submit "Create Account", class: "btn btn-warning px-4" %>
  <% else %>
    <%= f.submit "Update Account", class: "btn btn-warning px-4" %>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<div class="card m-3">
  <div class="card-body">
    <h1>Edit Account</h1>
    <p><%= render "form", user: @user %></p>
  </div>
</div>

app/views/users/index.html.erb
<div class="card m-3">
  <div class="card-body">
    <h1><%= pluralize(@users.size, "User") %></h1>
    <div class="container d-flex flex-wrap mt-4">
      <% @users.map do |user| %>
        <div class="border rounded mr-2 mb-2 d-inline-flex" style="width: 300px">
          <%= gravatar_for(user, styles: "rounded-left") %>
          <div class="p-2">
            <p class="m-0"><%= link_to user.name, user %></p>
            <small>created <%= time_ago_in_words(user.created_at) %> ago</small>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="card m-3">
  <div class="card-body">    
    <h1>Sign Up</h1>
    <p><%= render "form", user: @user %></p>
  </div>
</div>

app/views/users/show.html.erb
<div class="card m-3">
  <div class="card-body d-inline-flex flex-wrap justify-content-between">
    <div class="d-inline-flex flex-wrap">
      <div class="mr-4">
        <%= gravatar_for(@user) %>
      </div>
      <div class="flex-column">
        <h1><%= @user.name %></h1>
        <p><%= mail_to(@user.email) %></p>
      </div>
    </div>
    <% if current_user?(@user) %>
      <div class="flex-column">
        <%= link_to "Edit Account", edit_user_path(@user), class: "d-block btn btn-warning px-4 mb-2" %>
        <%= link_to "Delete Account", @user, method: :delete,
                    data: { confirm: "Are you shure?" },
                    class: "d-block btn btn-danger px-4 mb-2" %>
      </div>
    <% end %>
  </div>
</div>

<div class="d-flex flex-wrap">
  <% if @registrations.present? %>
    <div class="card m-3 flex-fill">
      <div class="card-body">
        <h3>Registrations</h3>
        <div class="d-flex flex-wrap mt-3">
          <% @registrations.each do |r| %>
            <div class="mb-2 mt-2 p-2">
              <div style="width: 150px; height: 150px;">
                <%= image_tag r.event.image_file_name, class: "event-image" %>
                <% if current_user?(@user) %>
                  <%= link_to "Cancel", event_registration_path(r.event, r), class: "btn btn-sm btn-danger btn-cancel rounded-0 mb-0", 
                            method: :delete, 
                            data: { confirm: "Really?" } %>
                <% end %>
              </div>
              <p class="m-0"><%= link_to r.event.name, r.event %></p>
              <small><%= time_ago_in_words(r.created_at) %> ago</small>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>

  <% if @liked_events.present? %>
    <div class="card m-3 flex-fill">
      <div class="card-body">
        <h3>Liked Events</h3>
        <div class="d-flex flex-wrap mt-3">
          <% @liked_events.each do |event| %>
            <div class="mb-2 mt-2 p-2">
              <%= image_tag event.image_file_name, class: "event-image" %>
              <p class="m-0"><%= link_to event.name, event %></p>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>