config/routes.rb
Rails.application.routes.draw do    
  root "events#index"

  get "events/filter/:filter" => "events#index", as: :filtered_events

  resources :events do
    resources :registrations
    resources :likes
  end

  resource :session, only: [:new, :create, :destroy]
  resources :users
  resources :categories
  
  get "signup" => "users#new"
end

app/models/event.rb
class Event < ApplicationRecord
  before_save :set_slug

  has_many :registrations, dependent: :destroy
  has_many :registered_users, through: :registrations, source: :user
  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user
  has_many :categorizations, dependent: :destroy
  has_many :categories, through: :categorizations

  validates :name, presence: true, uniqueness: true
  validates :location, presence: true
  validates :description, length: { minimum: 25 }
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  validates :capacity, numericality: { only_integer: true, greater_than: 0 }
  validates :image_file_name, format: {
    with: /\w+\.(jpg|png)\z/i,
    message: "must be a JPG or PNG image"
  }

  scope :past, -> { where("starts_at < ?", Time.now).order("starts_at") }
  scope :upcoming, -> { where("starts_at > ?", Time.now).order("starts_at") }
  scope :free, -> { upcoming.where(price: 0.0).order(:name) }
  scope :recent, ->(max=3) { past.limit(max) }

  def free?
    price.blank? || price.zero?
  end

  def sold_out?
    (capacity - registrations.size).zero?
  end

  def to_param
    slug
  end

  private

  def set_slug
    self.slug = name.parameterize
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :require_signin, except: [:index, :show]
  before_action :require_admin, except: [:index, :show]
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    case params[:filter]
    when "past"
      @events = Event.past
    when "free"
      @events = Event.free
    when "recent"
      @events = Event.recent
    else
      @events = Event.upcoming
    end
  end

  def show
    @likers = @event.likers
    @registered_users = @event.registered_users
    @categories = @event.categories
    if current_user
      @like = current_user.likes.find_by(event_id: @event.id)
    end
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: "Event successfully updated"
    else
      render :edit
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to @event, notice: "Event successfully created"
    else
      render :new
    end
  end

  def destroy
    @event.destroy
    redirect_to events_url
  end

  private

  def set_event
    @event = Event.find_by!(slug: params[:id])
  end

  def event_params
    params.require(:event).
      permit(:name, :description, :location, :price, :starts_at, 
            :capacity, :image_file_name, category_ids: [])
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def price(event)
    if event.free?
      "Free"
    else
      number_to_currency(event.price, precision: 0)
    end
  end

  def day_and_time(event)
    event.starts_at.strftime("%B %d at %I:%M %P")
  end
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |f| %>
  <div class="form-group row">

    <%= render "shared/errors", object: event %>

    <div class="col-sm-12 my-2">
      <%= f.label :name, class: "font-weight-bold" %>
      <%= f.text_field :name, autofocus: true, class: "form-control" %>
    </div>
    
    <div class="col-sm-12 my-2">
      <%= f.label :description, class: "font-weight-bold" %>
      <%= f.text_area :description, rows: 5, class: "form-control" %>
    </div>

    <div class="col-sm-12 my-2">
      <%= f.label :starts_at, class: "font-weight-bold" %>
      <%= f.datetime_select :starts_at, {ampm: true}, {class: "ml-2 mr-2 p-2 bg-light rounded"} %>
    </div>

    <div class="col-sm-12 my-2">
      <%= f.label :location, class: "font-weight-bold" %>
      <%= f.text_field :location, class: "form-control" %>
    </div>

    <div class="col-sm-12 my-2">
      <%= f.label :price, class: "font-weight-bold" %>
      <%= f.number_field :price, class: "form-control" %>
    </div>

     <div class="col-sm-12 my-2">
      <%= f.label :capacity, class: "font-weight-bold" %>
      <%= f.number_field :capacity, class: "form-control" %>
    </div>

    <div class="col-sm-12 my-2">
      <%= f.label :image_file_name, class: "font-weight-bold" %>
      <%= f.text_field :image_file_name, class: "form-control" %>
    </div>

    <div class="col-sm-12 my-2">
      <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) %>
    </div>
  </div>

  <%= f.submit class: "btn btn-warning px-4" %>
<% end %>

app/views/events/edit.html.erb
<div class="card m-3">
  <div class="card-body">
    <h1>Editing <%= @event.name %></h1>
    <%= render "form", event: @event %>
  </div>
</div>

app/views/events/index.html.erb
<% @events.map do |event| %>
  <div class="card m-3">
    <div class="card-body">
      <div class="d-inline-flex flex-wrap">
        <div class="mb-2">
          <%= image_tag event.image_file_name, class: "mr-5 event-image" %>
        </div>
        <div>
          <h2><%= link_to event.name, event %></h2>
          <p class="font-weight-bold d-inline"><%= day_and_time(event) %> in <%= event.location %></p>
            
          <% if event.free? %>
            <p class="badge badge-success ml-1"><%= price(event) %></p>
          <% else %>
            <p class="badge badge-warning ml-1"><%= price(event) %></p>
          <% end %>

          <p><%= truncate(event.description, length: 55, separator: ' ') %></p>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/events/new.html.erb
<div class="card m-3">
  <div class="card-body">
    <h1>Create a New Event</h1>
    <%= render "form", event: @event %>
  </div>
</div>

app/views/events/show.html.erb
<div class="card m-3">
  <div class="card-body">
    <div class="row">
      <div class="col-md-6 col-sm-12 mb-3">
        <%= image_tag @event.image_file_name, style: "width: 100%" %>
      </div>
      <div class="col-md-6 col-sm-12">
        <h1><%= @event.name %></h1>
        <p class="font-weight-bold d-inline-block mt-4"><%= day_and_time(@event) %> in <%= @event.location %></p>
        <p class="badge badge-light ml-1 border border-primary"><%= pluralize(@event.capacity, "spot") %> &bull; <%= price(@event) %></p>
        <p><%= @event.description %></p>
        <div class="mb-3">
          <% if @registered_users.include?(current_user) %>
            <span class="badge badge-warning">You are already registered</span>
          <% else %>
            <%= register_or_sold_out(@event) %>
          <% end%>
        </div>
        <p><%= link_to "Who's registered?", event_registrations_path(@event) %></p>
        <% if current_user %>
          <div class="list-group list-group-horizontal">
            <%= like_or_unlike_button(@event, @like) %>
            <div class="list-group-item text-secondary">
              <%= @likers.size %>
            </div>
          </div>
        <% end %>
        <% if current_user_admin? %>
          <div class="mt-3">
            <%= link_to "Edit", edit_event_path(@event), class: "btn btn-warning px-4" %>
            <%= link_to "Delete", @event, class: "btn btn-danger px-4", method: :delete, 
                                  data: { confirm: "Really?" } %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% if @likers.present? %>
<div class="card m-3">
  <div class="card-body">
    <h4>Liked by</h4>
    <ul>
      <% @likers.each do |user| %>
        <li>
          <%= link_to user.name, user %>
        </li>
      <% end %>
    </ul>
    <% end %>
  </div>
</div>

<% if @categories.present? %>
<div class="card m-3">
  <div class="card-body">
      <h4>Categories</h4>
      <ul>
        <% @categories.each do |c| %>
          <li>
            <%= c.name %>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
</div>